[package]
name = "faber-runtime"
version = "0.1.0"
edition = "2021"
description = "Runtime execution engine for Faber"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"