services:
  faber:
    container_name: faber-dev
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../.cargo:/faber/.cargo:ro
      - ../../src:/faber/src:ro
      - ../../crates:/faber/crates:ro
      - ../../Cargo.toml:/faber/Cargo.toml:ro
      - cargo-target:/faber/target
    environment:
      - API_KEY=just-a-test-api-key
      - CARGO_HOME=/usr/local/cargo
      - CACHE_ENABLED=true
    privileged: true
    ports:
      - '3000:3000'

volumes:
  cargo-target:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1
