services:
  faber:
    build: .
    env_file:
      - .env
    ports:
      - '3000:3000'

    volumes:
      - ./target/x86_64-unknown-linux-musl/debug:/opt/faber:ro
      - ./logs:/var/log/faber
    privileged: true
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
