[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:faber]
command=/opt/faber
directory=/opt
user=root
autostart=true
autorestart=true
startretries=3
startsecs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/faber.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
environment=HOME="/opt"
stopasgroup=true
killasgroup=true 