FROM debian:latest

# Install Rust and build dependencies
RUN apt update && apt install -y \
    curl \
    build-essential \
    pkg-config \
    libssl-dev \
    musl-tools \
    && rm -rf /var/lib/apt/lists/*

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Install the default target and musl target
RUN rustup default stable
RUN rustup target add x86_64-unknown-linux-musl

WORKDIR /faber 