FROM rust:1.88

RUN rustup target add x86_64-unknown-linux-musl

# Install g++ compiler, LLDB, and debugging tools
RUN apt update && apt install -y \
    curl \
    g++ \
    lldb \
    gdb \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch

WORKDIR /faber


ENTRYPOINT [ "/faber/scripts/lldb-start.sh" ]

