services:
  faber:
    build:
      context: ../
      dockerfile: docker/Dockerfile.prod
    privileged: true
    volumes:
      - ./config/:/faber/config:ro
    entrypoint: ['faber']
    ports:
      - 3000:3000/tcp
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    # restart: unless-stopped
